# Before Script
before_script:
  - docker-php-ext-enable zip
  - docker-php-ext-enable gd
  - composer config repo.packagist composer https://packagist.phpcomposer.com
  - composer install --no-progress --no-interaction
  - cp config/config{.default,}.php
  - php -v
  - php vendor/bin/phpdoccheck --directory=app

after_script:
#  - cat storage/logs/*.log

# Services
services:
#  - mysql:latest

#Stages
stages:
  - test

#PHP 7.0
php-7.0:
  type: test
  image: tetraweb/php:7.0
  script:
    - phpunit -c tests/units.sqlite.xml