git:
  depth: 3

language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/php.ini
  - touch storage/jitamin.sqlite
  - composer install
  - php vendor/bin/phpdoccheck --directory=app/
  - php artisan config:cache

script:
  - phpunit -c tests/units.$DB.xml
