git:
  depth: 3

language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

env:
#  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/php.ini
  - cp config/config{.default,}.php
  - composer install

script:
  - phpunit -c tests/units.$DB.xml
  - phpunit tests/configtest
